# Do not edit this file.

# This is the main application script. To run your web server (which you
# need to do before you can see your website in a browser), you would run
# `ruby main.rb` in Terminal.

# These lines invoke a tool call Bundler to automatically `require` several
# Ruby scripts that make this Web framework work.
require 'rubygems'
require 'bundler'
Bundler.require

# This is an add-on to the Web framework, which scans your code anew each time
# you save it. Otherwise, you would have to `Control + C` to stop the server
# and then run it again--each time you changed your code.
require 'sinatra/reloader'

# This sets up a class called MyApp, which you will use in controllers.
require 'sinatra/base'
class MyApp < Sinatra::Base
  set :sessions, true
  set :bind, '0.0.0.0'
end

# This line runs a `require` on each Ruby file in the 'controllers/' directory.
Dir[File.dirname(__FILE__) + '/controllers/*.rb'].each {|file| require file }